name = "FinEtoolsVibInFluids"
uuid = "bec31ec3-4858-4ad8-9f9e-aabdaa4a593b"
authors = ["Petr Krysl <pkrysl@ucsd.edu>"]
version = "0.2.0"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
FinEtools = "91bb5406-6c9a-523d-811d-0644c4229550"
FinEtoolsDeforLinear = "e9187c00-8bdd-11e9-1e70-7ba8303116a2"
FinEtoolsVoxelMesher = "508a6b02-8bde-11e9-1a67-e1104bdc04c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"

[compat]
julia = "^1.3"                                                                                                                                 
JSON = "^0.21"                                                                                                                                         
Literate = "^2.6"     
Arpack = "^0.4"
BenchmarkTools = "0.5"
TimerOutputs = "^0.5"
FinEtools = "^4"
FinEtoolsDeforLinear = "^0.2"                                                       
FinEtoolsVoxelMesher = "^0.2"
           
